In [1]:
import pandas as pnd
import numpy as nmp
from sklearn.model_selection import train_test_split ,GridSearchCV,cross_val_score
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
import xgboost as xgb
import pickle

In [2]:

data = pnd.read_excel(r"C:\Users\sbura\Desktop\Bitirme Projesi\Model Tabloları\Audi.xlsx")
data.drop(["Unnamed: 0"],axis=1,inplace=True)
data

,Fiyat,Yıl,Motor Gücü,Motor Hacmi,Kilometre,Boya,Değişen,Yakıt_Benzin,Yakıt_Dizel,Yakıt_LPG & Benzin,...,Model_A6 Sedan 3.0 Quattro,Model_A6 Sedan 3.0 TDI Quattro,Model_A6 Sedan 3.2 FSI Quattro,Model_A6 Sedan 40 TDI Design,Model_A6 Sedan 40 TDI Quattro Design,Model_A6 Sedan 40 TDI Quattro Sport,Model_A6 Sedan 40 TDI Sport,Model_A6 Sedan 45 TFSI Quattro Design,Model_A6 Sedan 45 TFSI Quattro Sport,Model_A6 Sedan 50 TDI Quattro Design
0,315000,2013,105,1598,245000,5,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,580000,2016,110,1598,38610,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,535000,2018,110,1598,88000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,155000,2003,150,1781,421000,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,365000,2011,126,1968,318000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1868,500000,2011,177,1998,201000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1869,279750,2005,163,1781,248000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1870,230000,2008,140,1968,286000,2,2,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1871,168000,2003,130,1984,264000,2,10,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1872,445000,2012,211,1984,203000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
x = data.drop("Fiyat",axis=1)
y = data["Fiyat"]
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=42)
xgb_tuned = xgb.XGBRegressor(colsample_bytree = 1,learning_rate = 0.2,max_depth = 2,n_estimators = 850)
xgb_tuned.fit(x_train,y_train)
pred = xgb_tuned.predict(x_test)

In [4]:
model_dosyasi= "Audi.pickle"
pickle.dump(xgb_tuned, open(model_dosyasi, 'wb'))