In [81]:
import pandas as pd
import numpy as np

In [112]:
df = pd.read_csv(r'C:\Users\Desktop\DERSLER\SIFIRDAN İLERİ SEVİYE PYTHON DERSLERİ\USED CARS DATASET\merged_final.csv',encoding="utf-16")

In [83]:
# boya-değişen = "Belirtilmemiş" -> boya = 0 , değişen = 0
# boya-değişen = "Tamamı boyalı" -> boya = 12, değişen = 0
# boya-değişen = "Tamamı değişen" -> boya = 0, değişen = 12
# boya-değişen = "boyalı" içeriyorsa v;e virgül yoksa ilk karakteri al boya sütununa at, değişen = 0
# boya-değişen = "değişen" içeriyorsa ve virgül yoksa ilk karakteri al değişen sütununa at, boya = 0

In [124]:
df.loc[df["Boya-değişen"] == "Belirtilmemiş", "Boya"] = 0
df.loc[df["Boya-değişen"] == "Belirtilmemiş", "Değişen"] = 0
df.loc[df["Boya-değişen"] == "Tamamı orjinal", "Boya"] = 0
df.loc[df["Boya-değişen"] == "Tamamı orjinal", "Değişen"] = 0
df.loc[df["Boya-değişen"] == "Tamamı boyalı", "Boya"] = 12
df.loc[df["Boya-değişen"] == "Tamamı boyalı", "Değişen"] = 0

In [85]:
def change_boya_degisen(obj):
    if ("değişen" in obj) and ("boyalı" in obj):
        return obj.replace(" değişen, ","-").replace(" boyalı","")
    else: return obj
df["Boya-değişen"] = df["Boya-değişen"].apply(change_boya_degisen)

In [86]:
df.loc[df["Boya-değişen"].str.contains("-"),"Boya"] = df["Boya-değişen"].str.split("-").str.get(0)
df.loc[df["Boya-değişen"].str.contains("-"),"Değişen"] = df["Boya-değişen"].str.split("-").str.get(1)

In [87]:
df[(df["Boya-değişen"].str.contains("değişen"))]["Boya-değişen"]

5        1 değişen
60       1 değişen
63       2 değişen
68       1 değişen
75       1 değişen
           ...
41671    3 değişen
41696    1 değişen
41742    2 değişen
41771    1 değişen
41793    2 değişen
Name: Boya-değişen, Length: 1820, dtype: object

In [88]:
df.drop([11869,23855],inplace = True)

In [89]:
df.loc[df["Boya-değişen"] == "Tamamı boyalı","Boya-değişen"] = "Tamamı boya"

In [90]:
df.loc[df["Boya-değişen"].str.contains("boyalı"),"Boya"] = df["Boya-değişen"].str.get(0)
df.loc[df["Boya-değişen"].str.contains("boyalı"),"Değişen"] = 0

In [91]:
df.loc[df["Boya-değişen"].str.contains("değişen"),"Değişen"] = df["Boya-değişen"].str.get(0)
df.loc[df["Boya-değişen"].str.contains("değişen"),"Boya"] = 0

In [116]:
df[df["Boya-değişen"] == "10 boyalı"]

,Index,Fiyat,Marka,Seri,Model,Yıl,Yakıt Tipi,Vites Tipi,Motor Gücü,Motor Hacmi,Kilometre,Boya-değişen
150,150,75000,Alfa Romeo,147,1.6 TS Distinctive,2005,LPG & Benzin,Düz,120,1598,233000,10 boyalı
155,155,60100,Alfa Romeo,147,1.6 TS Progression,2004,LPG & Benzin,Düz,120,1598,250000,10 boyalı
418,418,187000,Audi,A6,A6 Sedan 2.0 TDI,2008,Dizel,Otomatik,140,1968,274000,10 boyalı
1113,1113,267000,Audi,A3,A3 Sportback 1.6 TDI Attraction,2015,Dizel,Yarı Otomatik,110,1598,70000,10 boyalı
2002,2002,339900,Audi,A6,A6 Sedan 2.0 TDI,2011,Dizel,Yarı Otomatik,176,1801,315000,10 boyalı
...,...,...,...,...,...,...,...,...,...,...,...,...
39519,18832,105000,Mitsubishi,Colt,1.3 Invite,2009,Benzin,Düz,95,1332,90700,10 boyalı
39921,19234,98000,Nissan,Micra,1.2 Tekna,2008,Benzin,Düz,80,1240,168888,10 boyalı
39975,19288,66500,Nissan,Primera,1.6 SLX,1997,LPG & Benzin,Düz,100,1597,350000,10 boyalı
40585,19898,47000,Opel,Astra,1.4 GL,1994,LPG & Benzin,Düz,82,1389,315000,10 boyalı
41069,20382,54500,Opel,Astra,1.4 Classic,2001,LPG & Benzin,Düz,60,1389,249000,10 boyalı

In [93]:
def convert_value_Type(obj):
    return int(obj)

In [94]:
df["Boya"] = df["Boya"].apply(convert_value_Type)
df["Değişen"] = df["Değişen"].apply(convert_value_Type)

In [95]:
df["Boya-değişen"].unique()

array(['Belirtilmemiş', '1 boyalı', '1-1', '3-5', 'Tamamı boya',
       '1 değişen', '1-4', 'Tamamı orjinal', '3-2', '3-3', '5 boyalı',
       '9 boyalı', '2-11', '1-7', '1-12', '1-10', '3-9', '2 boyalı',
       '3 boyalı', '1-2', '1-8', '4-5', '2 değişen', '4 boyalı', '3-8',
       '12 boyalı', '4-9', '3-7', '2-2', '2-5', '2-3', '4-8', '1-9',
       '1-5', '2-6', '1-11', '3-10', '10 boyalı', '2-10', '2-8', '2-7',
       '1-3', '2-1', '6 boyalı', '1-6', '3 değişen', '2-4', '3-1', '2-9',
       '11 boyalı', '7 boyalı', '8 boyalı', '4 değişen', '3-4', '3-6',
       '5-4', '5 değişen', '5-3', '4-3', '4-7', '4-2', '4-4', '5-2',
       '7-5', '4-1', '5-1', '6-3', '5-5', '7-6', '6-7', '6 değişen',
       '4-6', '5-7', '5-8', '7 değişen', '6-4', '5-6', '7-2', '7-4',
       '6-1', '6-2', '12 değişen', '6-6', '7-3'], dtype=object)

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41813 entries, 0 to 41814
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         41813 non-null  int64
 1   Fiyat         41813 non-null  int64
 2   Marka         41813 non-null  object
 3   Seri          41813 non-null  object
 4   Model         41813 non-null  object
 5   Yıl           41813 non-null  int64
 6   Yakıt Tipi    41813 non-null  object
 7   Vites Tipi    41813 non-null  object
 8   Motor Gücü    41813 non-null  int64
 9   Motor Hacmi   41813 non-null  int64
 10  Kilometre     41813 non-null  int64
 11  Boya-değişen  41813 non-null  object
 12  Boya          41813 non-null  int64
 13  Değişen       41813 non-null  int64
dtypes: int64(8), object(6)
memory usage: 5.8+ MB

In [97]:
df

,Index,Fiyat,Marka,Seri,Model,Yıl,Yakıt Tipi,Vites Tipi,Motor Gücü,Motor Hacmi,Kilometre,Boya-değişen,Boya,Değişen
0,0,74500,Alfa Romeo,156,2.0 TS,2001,LPG & Benzin,Düz,155,1970,197600,Belirtilmemiş,0,0
1,1,100300,Alfa Romeo,156,1.6 TS Distinctive,2004,Benzin,Düz,120,1598,265450,1 boyalı,1,0
2,2,200000,Alfa Romeo,Giulietta,1.6 JTD Distinctive,2015,Dizel,Düz,105,1598,127000,1-1,1,1
3,3,65000,Alfa Romeo,147,1.6 TS Distinctive,2003,LPG & Benzin,Düz,120,1598,183500,3-5,3,5
4,4,86900,Alfa Romeo,147,1.6 TS Distinctive,2006,LPG & Benzin,Düz,120,1598,220000,Tamamı boya,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41810,21123,86500,Opel,Astra,1.6 Elegance,2001,LPG & Benzin,Düz,100,1598,325000,2-5,2,5
41811,21124,86000,Opel,Astra,1.6,2000,LPG & Benzin,Otomatik,100,1598,223000,2-10,2,10
41812,21125,245000,Opel,Insignia,1.6 CDTI Design,2016,Dizel,Otomatik,136,1598,159000,Belirtilmemiş,0,0
41813,21126,249900,Opel,Corsa,1.5 CDTI Edition,2020,Dizel,Düz,102,1499,19263,Belirtilmemiş,0,0
41814,21127,109750,Opel,Corsa,1.2 Enjoy,2007,Benzin,Düz,80,1229,150000,4 boyalı,4,0

In [98]:
df.drop("Index",axis=1,inplace=True)
df[["Boya","Değişen"]] = "-"
df

,Fiyat,Marka,Seri,Model,Yıl,Yakıt Tipi,Vites Tipi,Motor Gücü,Motor Hacmi,Kilometre,Boya-değişen,Boya,Değişen
0,74500,Alfa Romeo,156,2.0 TS,2001,LPG & Benzin,Düz,155,1970,197600,Belirtilmemiş,-,-
1,100300,Alfa Romeo,156,1.6 TS Distinctive,2004,Benzin,Düz,120,1598,265450,1 boyalı,-,-
2,200000,Alfa Romeo,Giulietta,1.6 JTD Distinctive,2015,Dizel,Düz,105,1598,127000,1-1,-,-
3,65000,Alfa Romeo,147,1.6 TS Distinctive,2003,LPG & Benzin,Düz,120,1598,183500,3-5,-,-
4,86900,Alfa Romeo,147,1.6 TS Distinctive,2006,LPG & Benzin,Düz,120,1598,220000,Tamamı boya,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...
41810,86500,Opel,Astra,1.6 Elegance,2001,LPG & Benzin,Düz,100,1598,325000,2-5,-,-
41811,86000,Opel,Astra,1.6,2000,LPG & Benzin,Otomatik,100,1598,223000,2-10,-,-
41812,245000,Opel,Insignia,1.6 CDTI Design,2016,Dizel,Otomatik,136,1598,159000,Belirtilmemiş,-,-
41813,249900,Opel,Corsa,1.5 CDTI Edition,2020,Dizel,Düz,102,1499,19263,Belirtilmemiş,-,-
41814,109750,Opel,Corsa,1.2 Enjoy,2007,Benzin,Düz,80,1229,150000,4 boyalı,-,-

In [99]:
df.drop("Boya-değişen",axis=1,inplace=True)

In [100]:
df.drop("Model",axis=1,inplace=True)

In [101]:
df

,Fiyat,Marka,Seri,Yıl,Yakıt Tipi,Vites Tipi,Motor Gücü,Motor Hacmi,Kilometre,Boya,Değişen
0,74500,Alfa Romeo,156,2001,LPG & Benzin,Düz,155,1970,197600,-,-
1,100300,Alfa Romeo,156,2004,Benzin,Düz,120,1598,265450,-,-
2,200000,Alfa Romeo,Giulietta,2015,Dizel,Düz,105,1598,127000,-,-
3,65000,Alfa Romeo,147,2003,LPG & Benzin,Düz,120,1598,183500,-,-
4,86900,Alfa Romeo,147,2006,LPG & Benzin,Düz,120,1598,220000,-,-
...,...,...,...,...,...,...,...,...,...,...,...
41810,86500,Opel,Astra,2001,LPG & Benzin,Düz,100,1598,325000,-,-
41811,86000,Opel,Astra,2000,LPG & Benzin,Otomatik,100,1598,223000,-,-
41812,245000,Opel,Insignia,2016,Dizel,Otomatik,136,1598,159000,-,-
41813,249900,Opel,Corsa,2020,Dizel,Düz,102,1499,19263,-,-
41814,109750,Opel,Corsa,2007,Benzin,Düz,80,1229,150000,-,-

In [102]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder = LabelEncoder()
onehotencoder = OneHotEncoder(sparse=False)
yeni_df = df[df["Marka"] == "Alfa Romeo"]
yeni_df["Yakıt Tipi"] = labelencoder.fit_transform(yeni_df["Yakıt Tipi"])
yeni_df[yeni_df["Marka"] == "Alfa Romeo"]["Vites Tipi"] = labelencoder.fit_transform(yeni_df["Vites Tipi"])
encoded_marka = onehotencoder.fit_transform(yeni_df[["Marka"]])
encoded_Seri = onehotencoder.fit_transform(yeni_df[["Seri"]])

<ipython-input-102-51fac7997ad2>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yeni_df["Yakıt Tipi"] = labelencoder.fit_transform(yeni_df["Yakıt Tipi"])

In [103]:
len(encoded_marka[0])

1

In [104]:
def marka_list():
    liste = []
    for i in range(len(encoded_marka[0])):
        liste.append(("Marka_"+str(i+1)))
    return liste

In [105]:
def seri_list():
    liste = []
    for i in range(len(encoded_Seri[0])):
        liste.append("Seri_"+str(i+1))
    return liste

In [106]:
yeni_df[marka_list()] = encoded_marka
yeni_df[seri_list()] = encoded_Seri

<ipython-input-106-ae9ad0c38b96>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yeni_df[marka_list()] = encoded_marka
C:\Users\yasin\anaconda3\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)
<ipython-input-106-ae9ad0c38b96>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  yeni_df[seri_list()] = encoded_Seri

In [107]:
yeni_df.drop("Marka",axis=1,inplace=True)

C:\Users\yasin\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [108]:
yeni_df.drop("Seri",axis=1,inplace=True)

In [30]:
yeni_df

,Fiyat,Yıl,Yakıt Tipi,Vites Tipi,Motor Gücü,Motor Hacmi,Kilometre,Boya,Değişen,Marka_1,...,Seri_451,Seri_452,Seri_453,Seri_454,Seri_455,Seri_456,Seri_457,Seri_458,Seri_459,Seri_460
0,74500,2001,2,0,155,1970,197600,0,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,100300,2004,0,0,120,1598,265450,1,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,200000,2015,1,0,105,1598,127000,1,1,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,65000,2003,2,0,120,1598,183500,3,5,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,86900,2006,2,0,120,1598,220000,11,0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41810,86500,2001,2,0,100,1598,325000,2,5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41811,86000,2000,2,1,100,1598,223000,2,10,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41812,245000,2016,1,1,136,1598,159000,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41813,249900,2020,1,0,102,1499,19263,0,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41814,109750,2007,0,0,80,1229,150000,4,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
y=yeni_df[(yeni_df["Marka"] == "Alfa Romeo")]
y.head()

KeyError: 'Marka'

In [34]:
import math
from math import sqrt
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import linear_model

In [35]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.30 , random_state=85 )
model= linear_model.LinearRegression()
model.fit(x_train, y_train)
pred = model.predict(x_test)
print("Train Test:", pred[0:20])

Train Test: [130000.  93000.  95000. 435000. 199500. 169000. 148900. 843000. 260000.
 260000. 136000.  50000. 113500. 126800.  87000.  19750.  91500. 207500.
  78500.  88500.]

In [37]:
mse = mean_absolute_error(y_test,pred)
print("\nMAE: ", mse)

MAE:  1.019439770694979e-10