In [1]:
import pandas as pnd
import numpy as nmp
from sklearn.model_selection import train_test_split ,GridSearchCV,cross_val_score
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
import xgboost as xgb
import pickle

In [2]:

data = pnd.read_excel(r"C:\Users\sbura\Desktop\Bitirme Projesi\Model Tabloları\Chevrolet.xlsx")
data.drop(["Unnamed: 0"],axis=1,inplace=True)
data

,Fiyat,Yıl,Motor Gücü,Motor Hacmi,Kilometre,Boya,Değişen,Yakıt_Benzin,Yakıt_Dizel,Yakıt_LPG & Benzin,...,Model_1.6 SE,Model_1.6 SX,Model_1.6 Sport,Model_1.6 Sport Plus,Model_1.6 WTCC,Model_1.6 WTCC Edition,Model_1.6 WTCC Edition Plus,Model_2.0 D CDX,Model_2.0 D LT,Model_2.0 D LTZ
0,169000,2011,100,1398,79000,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,133500,2011,100,1398,215000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,145000,2007,94,1399,129000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,139500,2006,94,1399,185000,1,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,122500,2005,109,1598,206000,1,2,0,0,1,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1444,195000,2012,163,1998,190000,2,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1
1445,192000,2011,124,1598,118000,2,2,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1446,210000,2010,113,1598,114000,2,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1447,225000,2012,124,1598,170000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1448,129000,2007,94,1399,141000,2,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [3]:
x = data.drop("Fiyat",axis=1)
y = data["Fiyat"]
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=42)
xgb_tuned = xgb.XGBRegressor(colsample_bytree = 0.4,learning_rate = 0.01,max_depth = 4,n_estimators = 850)
xgb_tuned.fit(x_train,y_train)
pred = xgb_tuned.predict(x_test)

In [4]:
model_dosyasi= "Chevrolet.pickle"
pickle.dump(xgb_tuned, open(model_dosyasi, 'wb'))