In [1]:
import pandas as pnd
import numpy as nmp
from sklearn.model_selection import train_test_split ,GridSearchCV,cross_val_score
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
import xgboost as xgb
import pickle

In [2]:

data = pnd.read_excel(r"C:\Users\sbura\Desktop\Bitirme Projesi\Model Tabloları\Honda.xlsx")
data.drop(["Unnamed: 0"],axis=1,inplace=True)
data

,Fiyat,Yıl,Motor Gücü,Motor Hacmi,Kilometre,Boya,Değişen,Yakıt_Benzin,Yakıt_Dizel,Yakıt_LPG & Benzin,...,Model_1.8 i-VTEC Executive,Model_2.0 ES,Model_2.0 EX,Model_2.0 Executive,Model_2.0 LS,Model_2.0 Sport,Model_2.0 TD,Model_2.0 Type-R,Model_2.2 CTDi,Model_2.4 Executive
0,109900,1999,90,1396,303000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,173000,2006,110,1590,297000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,145000,2002,110,1590,310000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,255950,2012,125,1595,183000,6,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,165750,2005,110,1590,242000,0,2,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2042,500000,2020,125,1597,7850,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2043,126000,2010,83,1339,230000,2,8,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2044,325000,2017,125,1597,133750,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2045,310000,2012,125,1595,139000,2,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2046,245000,2008,125,1595,183000,5,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
x = data.drop("Fiyat",axis=1)
y = data["Fiyat"]
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=42)
xgb_tuned = xgb.XGBRegressor(colsample_bytree = 0.5,learning_rate = 0.1,max_depth = 3,n_estimators = 350)
xgb_tuned.fit(x_train,y_train)
pred = xgb_tuned.predict(x_test)

In [4]:
model_dosyasi= "Honda.pickle"
pickle.dump(xgb_tuned, open(model_dosyasi, 'wb'))