In [1]:
import pandas as pnd
import numpy as nmp
from sklearn.model_selection import train_test_split ,GridSearchCV,cross_val_score
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
import xgboost as xgb
import pickle

In [2]:

data = pnd.read_excel(r"C:\Users\sbura\Desktop\Bitirme Projesi\Model Tabloları\Nissan.xlsx")
data.drop(["Unnamed: 0"],axis=1,inplace=True)
data

,Fiyat,Yıl,Motor Gücü,Motor Hacmi,Kilometre,Boya,Değişen,Yakıt_Benzin,Yakıt_Dizel,Yakıt_LPG & Benzin,...,Model_1.6 Tekna Plus,Model_1.6 Visia,Model_1.8 Comfort,Model_1.8 Luxury,Model_2.0 GT,Model_2.0 SE,Model_2.0 SRi,Model_2.0 TD Luxe,Model_2.0 Tekna,Model_2.2 TD
0,209900,2013,76,1200,84000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,104000,2005,98,1498,300000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,132500,2005,109,1596,178000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,115000,2004,109,1596,286000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,165000,2008,80,1240,190000,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,110000,2006,98,1498,225000,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
613,110000,2002,90,1497,257800,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
614,122800,2007,65,1240,147000,1,6,1,0,0,...,0,0,0,0,0,0,0,0,0,0
615,200000,2011,80,1198,147000,1,3,0,0,1,...,0,0,0,0,0,0,0,0,0,0
616,116000,2005,109,1596,283000,1,11,0,0,1,...,0,1,0,0,0,0,0,0,0,0

In [3]:
x = data.drop("Fiyat",axis=1)
y = data["Fiyat"]
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=42)
xgb_tuned = xgb.XGBRegressor(colsample_bytree = 1,learning_rate = 0.1,max_depth = 2,n_estimators = 150)
xgb_tuned.fit(x_train,y_train)
pred = xgb_tuned.predict(x_test)

In [4]:
model_dosyasi= "Nissan.pickle"
pickle.dump(xgb_tuned, open(model_dosyasi, 'wb'))