In [1]:
import pandas as pnd
import numpy as nmp
from sklearn.model_selection import train_test_split ,GridSearchCV,cross_val_score
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
import xgboost as xgb
import pickle

In [2]:

data = pnd.read_excel(r"C:\Users\sbura\Desktop\Bitirme Projesi\Model Tabloları\Opel.xlsx")
data.drop(["Unnamed: 0"],axis=1,inplace=True)
data

,Fiyat,Yıl,Motor Gücü,Motor Hacmi,Kilometre,Boya,Değişen,Yakıt_Benzin,Yakıt_Dizel,Yakıt_LPG & Benzin,...,Model_2.0 DTI CD,Model_2.0 DTI Comfort,Model_2.0 GL,Model_2.0 GLS,Model_2.0 GT,Model_2.0 Sport,Model_2.2 DTI Elegance,Model_2.2 Elegance,Model_2.2 GTS,Model_2.8 OPC
0,205000,2011,100,1364,183000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,161750,2008,90,1248,232000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,264750,2017,115,1598,79000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,85000,1996,136,1998,332000,2,9,0,0,1,...,0,0,0,1,0,0,0,0,0,0
4,403000,2021,76,1200,22380,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2152,129500,2000,100,1598,264000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2153,195000,2015,70,1229,186000,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2154,225000,2012,140,1364,245800,3,2,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2155,375000,2015,136,1598,108000,5,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2156,298000,2019,90,1398,44000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
x = data.drop("Fiyat",axis=1)
y = data["Fiyat"]
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=42)
xgb_tuned = xgb.XGBRegressor(colsample_bytree = 0.8,learning_rate = 0.1,max_depth = 4,n_estimators = 300)
xgb_tuned.fit(x_train,y_train)
pred = xgb_tuned.predict(x_test)

In [5]:
model_dosyasi= "Opel.pickle"
pickle.dump(xgb_tuned, open(model_dosyasi, 'wb'))