In [1]:
import pandas as pnd
import numpy as nmp
from sklearn.model_selection import train_test_split ,GridSearchCV,cross_val_score
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
import xgboost as xgb
import pickle

data = pnd.read_excel(r"C:\Users\sbura\Desktop\Bitirme Projesi\Model Tabloları\Peugeot.xlsx")
data.drop(["Unnamed: 0"],axis=1,inplace=True)
data

,Fiyat,Yıl,Motor Gücü,Motor Hacmi,Kilometre,Boya,Değişen,Yakıt_Benzin,Yakıt_Dizel,Yakıt_LPG & Benzin,...,Model_2.0 GTI,Model_2.0 HDi Active,Model_2.0 HDi Allure,Model_2.0 HDi Comfort,Model_2.0 HDi Executive Premium,Model_2.0 HDi GT Line,Model_2.0 HDi Premium,Model_2.0 HDi XT,Model_2.0 Premium,Model_3.0 Premium
0,799000,2020,130,1499,26105,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,193000,2015,83,1199,102500,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,151000,2004,110,1587,148000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,176000,2009,91,1360,130000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,176750,2015,93,1560,172000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1963,185000,2015,93,1560,181000,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1964,365000,2016,122,1560,315000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1965,90000,2006,69,1398,300000,2,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1966,122000,2007,76,1360,219500,5,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1967,218500,2015,93,1560,185000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [2]:
x = data.drop("Fiyat",axis=1)
y = data["Fiyat"]
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=42)
xgb_tuned = xgb.XGBRegressor(colsample_bytree = 0.9,learning_rate = 0.1,max_depth = 4,n_estimators = 300)
xgb_tuned.fit(x_train,y_train)
pred = xgb_tuned.predict(x_test)

In [3]:
model_dosyasi= "Peugeot.pickle"
pickle.dump(xgb_tuned, open(model_dosyasi, 'wb'))