In [1]:
import pandas as pnd
import numpy as nmp
from sklearn.model_selection import train_test_split ,GridSearchCV,cross_val_score
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
import xgboost as xgb
import pickle

data = pnd.read_excel(r"C:\Users\sbura\Desktop\Bitirme Projesi\Model Tabloları\Seat.xlsx")
data.drop(["Unnamed: 0"],axis=1,inplace=True)
data

,Fiyat,Yıl,Motor Gücü,Motor Hacmi,Kilometre,Boya,Değişen,Yakıt_Benzin,Yakıt_Dizel,Yakıt_LPG & Benzin,...,Model_1.9 TDI Signo Vario,Model_1.9 TDI Sport,Model_1.9 TDI Stella,Model_1.9 TDI Stylance,Model_1.9 TDI Style,Model_2.0 Cupra,Model_2.0 TDI Stylance,Model_2.0 TFSI Cupra,Model_2.0 TFSI FR,Model_2.0 TFSI Sport
0,119000,2008,80,1422,300000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,495000,2019,115,1598,71000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,276500,2011,105,1598,49500,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,72000,2000,100,1595,350000,10,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,225000,2014,105,1598,190000,1,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,322000,2014,105,1598,107000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2107,205000,2011,125,1390,118000,1,6,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2108,385000,2017,105,1598,122000,3,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2109,309999,2016,110,1197,132000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2110,300000,2015,105,1598,178500,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [2]:
x = data.drop("Fiyat",axis=1)
y = data["Fiyat"]
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=42)
xgb_tuned = xgb.XGBRegressor(colsample_bytree = 0.5,learning_rate = 0.01,max_depth = 6,n_estimators = 750)
xgb_tuned.fit(x_train,y_train)
pred = xgb_tuned.predict(x_test)

In [3]:
model_dosyasi= "Seat.pickle"
pickle.dump(xgb_tuned, open(model_dosyasi, 'wb'))