In [1]:
import pandas as pnd
import numpy as nmp
from sklearn.model_selection import train_test_split ,GridSearchCV,cross_val_score
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
import xgboost as xgb
import pickle

data = pnd.read_excel(r"C:\Users\sbura\Desktop\Bitirme Projesi\Model Tabloları\Skoda.xlsx")
data.drop(["Unnamed: 0"],axis=1,inplace=True)
data

,Fiyat,Yıl,Motor Gücü,Motor Hacmi,Kilometre,Boya,Değişen,Yakıt_Benzin,Yakıt_Dizel,Yakıt_LPG & Benzin,...,Model_1.9 TDI Ambiente,Model_1.9 TDI Comfort,Model_1.9 TDI Elegance,Model_2.0 TDI Elegance,Model_2.0 TDI Laurin&Klement,Model_2.0 TDI Prestige,Model_2.0 TDI RS,Model_2.0 TSI RS,Model_2.5 TDI Comfort,Model_2.5 TDI Elegance
0,378500,2014,105,1598,138000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,172000,2014,70,1198,216000,2,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,409000,2015,110,1598,123000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,605000,2021,101,1200,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,775000,2021,150,1498,4999,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006,480000,2018,120,1598,140000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2007,459750,2019,115,1598,62000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2008,359750,2017,115,1598,123000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2009,110000,2006,75,1422,236000,5,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2010,318500,2016,90,1422,130000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [2]:
x = data.drop("Fiyat",axis=1)
y = data["Fiyat"]
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=42)
xgb_tuned = xgb.XGBRegressor(colsample_bytree = 0.4,learning_rate = 0.1,max_depth = 3,n_estimators = 300)
xgb_tuned.fit(x_train,y_train)
pred = xgb_tuned.predict(x_test)

In [3]:
model_dosyasi= "Skoda.pickle"
pickle.dump(xgb_tuned, open(model_dosyasi, 'wb'))