In [1]:
import pandas as pnd
import numpy as nmp
from sklearn.model_selection import train_test_split ,GridSearchCV,cross_val_score
from sklearn.metrics import r2_score , mean_squared_error , mean_absolute_error
import xgboost as xgb
import pickle

data = pnd.read_excel(r"C:\Users\sbura\Desktop\Bitirme Projesi\Model Tabloları\Volkswagen.xlsx")
data.drop(["Unnamed: 0"],axis=1,inplace=True)
data

,Fiyat,Yıl,Motor Gücü,Motor Hacmi,Kilometre,Boya,Değişen,Yakıt_Benzin,Yakıt_Dizel,Yakıt_LPG & Benzin,...,Model_2.0 FSi Highline,Model_2.0 TDi BlueMotion Comfortline,Model_2.0 TDi BlueMotion Elegance,Model_2.0 TDi BlueMotion Highline,Model_2.0 TDi Comfortline,Model_2.0 TDi Exclusive,Model_2.0 TDi Goal,Model_2.0 TDi Highline,Model_2.0 TSi R,Model_2.0 Trendline
0,80000,1997,75,1598,250000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,127500,2001,105,1595,386000,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,313000,2012,122,1390,175000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,168000,2005,115,1598,200000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,313750,2017,90,1422,172000,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2090,150000,2006,75,1390,131000,4,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2091,185000,2006,75,1390,160000,0,3,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2092,165000,2004,115,1598,260000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2093,220000,2012,105,1197,93000,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2094,270000,2013,85,1390,160000,3,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [2]:
x = data.drop("Fiyat",axis=1)
y = data["Fiyat"]
x_train, x_test , y_train, y_test = train_test_split(x,y,test_size=0.30,random_state=42)
xgb_tuned = xgb.XGBRegressor(colsample_bytree = 0.4,learning_rate = 0.1,max_depth = 3,n_estimators = 600)
xgb_tuned.fit(x_train,y_train)
pred = xgb_tuned.predict(x_test)

In [3]:
model_dosyasi= "Volkswagen.pickle"
pickle.dump(xgb_tuned, open(model_dosyasi, 'wb'))